# Generated by Django 4.1.2 on 2022-10-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_lead_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='lead_test',
            new_name='lead_text',
        ),
    ]
